// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webHuyBeo.Models;

#nullable disable

namespace webHuyBeo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260711162631_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("webHuyBeo.Models.ChiTietDon", b =>
                {
                    b.Property<int>("ChiTietID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChiTietID"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DonHangID")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MonAnID")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ThoiGianBatDauCB")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianHoanThanh")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThaiBep")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ChiTietID");

                    b.HasIndex("DonHangID");

                    b.HasIndex("MonAnID");

                    b.ToTable("ChiTietDons");
                });

            modelBuilder.Entity("webHuyBeo.Models.ChiTietTopping", b =>
                {
                    b.Property<int>("ChiTietID")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("ToppingID")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("ChiTietID", "ToppingID");

                    b.HasIndex("ToppingID");

                    b.ToTable("ChiTietToppings");
                });

            modelBuilder.Entity("webHuyBeo.Models.DanhMuc", b =>
                {
                    b.Property<int>("DanhMucID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DanhMucID"));

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("DanhMucID");

                    b.ToTable("DanhMucs");
                });

            modelBuilder.Entity("webHuyBeo.Models.DonHang", b =>
                {
                    b.Property<int>("DonHangID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DonHangID"));

                    b.Property<string>("LoaiDon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("NgayHoanThanh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiDungID")
                        .HasColumnType("int");

                    b.Property<int>("PhienID")
                        .HasColumnType("int");

                    b.Property<string>("PhuongThucTT")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SoThuTu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TongGiamGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TrangThaiTT")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("DonHangID");

                    b.HasIndex("NguoiDungID");

                    b.HasIndex("PhienID");

                    b.ToTable("DonHangs");
                });

            modelBuilder.Entity("webHuyBeo.Models.DonHangKhuyenMai", b =>
                {
                    b.Property<int>("DonHangID")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("KhuyenMaiID")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<decimal>("SoTienGiam")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("DonHangID", "KhuyenMaiID");

                    b.HasIndex("KhuyenMaiID");

                    b.ToTable("DonHangKhuyenMais");
                });

            modelBuilder.Entity("webHuyBeo.Models.KhuyenMai", b =>
                {
                    b.Property<int>("KhuyenMaiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KhuyenMaiID"));

                    b.Property<decimal?>("DonToiThieu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GiaTri")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GiamToiDa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LoaiGiam")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLuongDaDung")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongToiDa")
                        .HasColumnType("int");

                    b.Property<string>("TenKM")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("KhuyenMaiID");

                    b.ToTable("KhuyenMais");
                });

            modelBuilder.Entity("webHuyBeo.Models.MonAn", b =>
                {
                    b.Property<int>("MonAnID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MonAnID"));

                    b.Property<bool>("ConBan")
                        .HasColumnType("bit");

                    b.Property<int>("DanhMucID")
                        .HasColumnType("int");

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GiaVon")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenMon")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MonAnID");

                    b.HasIndex("DanhMucID");

                    b.ToTable("MonAns");
                });

            modelBuilder.Entity("webHuyBeo.Models.MonAnTopping", b =>
                {
                    b.Property<int>("MonAnID")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("ToppingID")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("MonAnID", "ToppingID");

                    b.HasIndex("ToppingID");

                    b.ToTable("MonAnToppings");
                });

            modelBuilder.Entity("webHuyBeo.Models.NguoiDung", b =>
                {
                    b.Property<int>("NguoiDungID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NguoiDungID"));

                    b.Property<string>("Hoten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("NguoiDungID");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("NguoiDungs");
                });

            modelBuilder.Entity("webHuyBeo.Models.NhatKyDon", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogID"));

                    b.Property<int>("DonHangID")
                        .HasColumnType("int");

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiDungID")
                        .HasColumnType("int");

                    b.HasKey("LogID");

                    b.HasIndex("DonHangID");

                    b.HasIndex("NguoiDungID");

                    b.ToTable("NhatKyDons");
                });

            modelBuilder.Entity("webHuyBeo.Models.PhienOrder", b =>
                {
                    b.Property<int>("PhienID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhienID"));

                    b.Property<string>("MaToken")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PhienID");

                    b.ToTable("PhienOrders");
                });

            modelBuilder.Entity("webHuyBeo.Models.Topping", b =>
                {
                    b.Property<int>("ToppingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ToppingID"));

                    b.Property<decimal>("GiaThem")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenTopping")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ToppingID");

                    b.ToTable("Toppings");
                });

            modelBuilder.Entity("webHuyBeo.Models.ChiTietDon", b =>
                {
                    b.HasOne("webHuyBeo.Models.DonHang", "DonHang")
                        .WithMany("ChiTietDons")
                        .HasForeignKey("DonHangID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("webHuyBeo.Models.MonAn", "MonAn")
                        .WithMany("ChiTietDons")
                        .HasForeignKey("MonAnID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("MonAn");
                });

            modelBuilder.Entity("webHuyBeo.Models.ChiTietTopping", b =>
                {
                    b.HasOne("webHuyBeo.Models.ChiTietDon", "ChiTietDon")
                        .WithMany("ChiTietToppings")
                        .HasForeignKey("ChiTietID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("webHuyBeo.Models.Topping", "Topping")
                        .WithMany("ChiTietToppings")
                        .HasForeignKey("ToppingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiTietDon");

                    b.Navigation("Topping");
                });

            modelBuilder.Entity("webHuyBeo.Models.DonHang", b =>
                {
                    b.HasOne("webHuyBeo.Models.NguoiDung", "NguoiDung")
                        .WithMany("DonHangs")
                        .HasForeignKey("NguoiDungID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("webHuyBeo.Models.PhienOrder", "PhienOrder")
                        .WithMany("DonHangs")
                        .HasForeignKey("PhienID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");

                    b.Navigation("PhienOrder");
                });

            modelBuilder.Entity("webHuyBeo.Models.DonHangKhuyenMai", b =>
                {
                    b.HasOne("webHuyBeo.Models.DonHang", "DonHang")
                        .WithMany("DonHangKhuyenMais")
                        .HasForeignKey("DonHangID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("webHuyBeo.Models.KhuyenMai", "KhuyenMai")
                        .WithMany("DonHangKhuyenMais")
                        .HasForeignKey("KhuyenMaiID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("KhuyenMai");
                });

            modelBuilder.Entity("webHuyBeo.Models.MonAn", b =>
                {
                    b.HasOne("webHuyBeo.Models.DanhMuc", "DanhMuc")
                        .WithMany("MonAns")
                        .HasForeignKey("DanhMucID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanhMuc");
                });

            modelBuilder.Entity("webHuyBeo.Models.MonAnTopping", b =>
                {
                    b.HasOne("webHuyBeo.Models.MonAn", "MonAn")
                        .WithMany("MonAnToppings")
                        .HasForeignKey("MonAnID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("webHuyBeo.Models.Topping", "Topping")
                        .WithMany("MonAnToppings")
                        .HasForeignKey("ToppingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonAn");

                    b.Navigation("Topping");
                });

            modelBuilder.Entity("webHuyBeo.Models.NhatKyDon", b =>
                {
                    b.HasOne("webHuyBeo.Models.DonHang", "DonHang")
                        .WithMany("NhatKyDons")
                        .HasForeignKey("DonHangID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("webHuyBeo.Models.NguoiDung", "NguoiDung")
                        .WithMany("NhatKyDons")
                        .HasForeignKey("NguoiDungID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DonHang");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("webHuyBeo.Models.ChiTietDon", b =>
                {
                    b.Navigation("ChiTietToppings");
                });

            modelBuilder.Entity("webHuyBeo.Models.DanhMuc", b =>
                {
                    b.Navigation("MonAns");
                });

            modelBuilder.Entity("webHuyBeo.Models.DonHang", b =>
                {
                    b.Navigation("ChiTietDons");

                    b.Navigation("DonHangKhuyenMais");

                    b.Navigation("NhatKyDons");
                });

            modelBuilder.Entity("webHuyBeo.Models.KhuyenMai", b =>
                {
                    b.Navigation("DonHangKhuyenMais");
                });

            modelBuilder.Entity("webHuyBeo.Models.MonAn", b =>
                {
                    b.Navigation("ChiTietDons");

                    b.Navigation("MonAnToppings");
                });

            modelBuilder.Entity("webHuyBeo.Models.NguoiDung", b =>
                {
                    b.Navigation("DonHangs");

                    b.Navigation("NhatKyDons");
                });

            modelBuilder.Entity("webHuyBeo.Models.PhienOrder", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("webHuyBeo.Models.Topping", b =>
                {
                    b.Navigation("ChiTietToppings");

                    b.Navigation("MonAnToppings");
                });
#pragma warning restore 612, 618
        }
    }
}
